# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 8,14 * * *"
      timezone: "Europe/Berlin"
    allow:
      - dependency-name: "com.wire:avs"
      - dependency-name: "com.wire:avs-kmp"
      - dependency-name: "com.wire:core-crypto-android"
      - dependency-name: "com.wire:core-crypto-jvm"
      - dependency-name: "io.github.mohamadjaara:core-crypto-kmp"
    commit-message:
      prefix: "chore(deps): [WPB-9777] "
