# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

DISABLE_LINTERS:
  - SPELL_CSPELL
  - EDITORCONFIG_EDITORCONFIG_CHECKER
