[tool.towncrier]
name = "Kalium"
directory = "changelog.d"
filename = "CHANGELOG.md"
title_format = "# Consumer-facing changes"
issue_format = ""
wrap = false

[[tool.towncrier.type]]
directory = "added"
name = "Added"

[[tool.towncrier.type]]
directory = "changed"
name = "Changed"

[[tool.towncrier.type]]
directory = "deprecated"
name = "Deprecated"

[[tool.towncrier.type]]
directory = "removed"
name = "Removed"

[[tool.towncrier.type]]
directory = "fixed"
name = "Fixed"

[[tool.towncrier.type]]
directory = "security"
name = "Security"
