{
 "title": "Infinite Monkeys",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Conversations",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "g_conversations", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Number of Members/Conversation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 1 },
   "targets": [
    { "expr": "avg(g_conversationMembers)", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Errors per Actions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "max by(action) (c_errors_total)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Currently Logged Out Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max by(testCase, domain) (g_loggedOutUsers)",
     "legendFormat": "{{testCase}} - {{domain}}"
    }
   ]
  },
  {
   "title": "Currently Logged In Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "max by(testCase, domain) (g_loggedInUsers)",
     "legendFormat": "{{testCase}} - {{domain}}"
    }
   ]
  },
  { "title": "Actions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Distribution per 1m: Create Conversation time taken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_CREATE_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_CREATE_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_CREATE_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_CREATE_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "t_CREATE_CONVERSATION_seconds_sum/t_CREATE_CONVERSATION_seconds_count",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Distribution per 1m: Destroy Conversation time taken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_DESTROY_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_DESTROY_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_DESTROY_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_DESTROY_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "t_DESTROY_CONVERSATION_seconds_sum/t_DESTROY_CONVERSATION_seconds_count",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Distribution per 1m: Add User To Conversation time taken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_ADD_USER_TO_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_ADD_USER_TO_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_ADD_USER_TO_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_ADD_USER_TO_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "t_ADD_USER_TO_CONVERSATION_seconds_sum/t_ADD_USER_TO_CONVERSATION_seconds_count",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Distribution per 1m: Leave Conversation time taken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_LEAVE_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_LEAVE_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_LEAVE_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_LEAVE_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "t_LEAVE_CONVERSATION_seconds_sum/t_LEAVE_CONVERSATION_seconds_count",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Distribution per 1m: Send Messages time taken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_SEND_MESSAGE_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_SEND_MESSAGE_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_SEND_MESSAGE_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_SEND_MESSAGE_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "t_SEND_MESSAGE_seconds_sum/t_SEND_MESSAGE_seconds_count",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Distribution per 1m: Send Request time taken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_SEND_REQUEST_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_SEND_REQUEST_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_SEND_REQUEST_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_SEND_REQUEST_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "t_SEND_REQUEST_seconds_sum/t_SEND_REQUEST_seconds_count",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Distribution per 1m: Login time taken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_LOGIN_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_LOGIN_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_LOGIN_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_LOGIN_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "t_LOGIN_seconds_sum/t_LOGIN_seconds_count",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Distribution per 1m: Reconnect time taken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_RECONNECT_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_RECONNECT_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_RECONNECT_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_RECONNECT_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "t_RECONNECT_seconds_sum/t_RECONNECT_seconds_count",
     "legendFormat": "Avg"
    }
   ]
  }
 ]
}