apiVersion: v2

name: infinitemonkeys
type: application
version: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts/
    version: 56.20.0

