name: Setup Java and Gradle
description: Setup java and gradle with cache for jobs
inputs:
  enable-kvm:
    description: 'Whether to enable KVM'
    required: false
    default: false
runs:
  using: composite
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Gradle Cache
      uses: gradle/actions/setup-gradle@v3

    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@v3

    - name: Enable KVM (Linux only)
      if: ${{ inputs.enable-kvm == 'true' && runner.os == 'Linux' }}
      shell: bash
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
