- hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  roles:
  - role: common

- hosts: node018
  become: yes
  become_user: root
  gather_facts: yes
  roles:
  - role: kalium-testservice
