package configModels


enum class Configs {
    accountsUrl,
    allowChangeOfEmail,
    allowMarketingCommunication,
    allowSSO,
    allow_account_creation,
    app_lock_timeout,
    backendUrl,
    blacklistHost,
    block_on_jailbreak_or_root,
    block_on_password_policy,
    candidate,
    certificatePin,
    countly_app_key,
    countly_server_url,
    custom_url_scheme,
    dev,
    enableBlacklist,
    experimental,
    fdroid,
    file_restriction_enabled,
    file_restriction_list,
    firebaseAppId,
    firebasePushSenderId,
    force_app_lock,
    force_constant_bitrate_calls,
    force_hide_screen_content,
    force_private_keyboard,
    http_proxy_port,
    http_proxy_url,
    internal,
    keep_websocket_on,
    maxAccounts,
    new_password_maximum_length,
    new_password_minimum_length,
    password_max_attempts,
    wipe_on_cookie_invalid,
    prod,
    submitCrashReports,
    supportEmail,
    teamsUrl,
    web_link_preview,
    websiteUrl,
    websocketUrl,

    certificate,
    domain,

    _comment,
    appName,
    applicationId,
    developer_features_enabled,
    launcherIcon,
    logging_enabled,
    safe_logging,
    userId
}


