package configModels


enum class Configs(val value: String) {
    ACCOUNT_URL("accountsUrl"),
    ALLOW_CHANGE_OF_EMAIL("allowChangeOfEmail"),
    ALLOW_MARKETING_COMMUNICATION("allowMarketingCommunication"),
    ALLOW_SSO("allowSSO"),
    ALLOW_ACCOUNT_CREATION("allow_account_creation"),
    APP_LOCK_TIMEOUT("app_lock_timeout"),
    BACKEND_URL("backendUrl"),
    BLACKLIST_HOST("blacklistHost"),
    BLOCK_ON_JAILBREAK_OR_ROOT("block_on_jailbreak_or_root"),
    BLOCK_ON_PASSWORD_POLICY("block_on_password_policy"),
    CANDIDATE("candidate"),
    CERTIFICATE_PIN("certificatePin"),
    COUNTLY_APP_KEY("countly_app_key"),
    COUNTLY_SERVER_URL("countly_server_url"),
    CUSTOM_URL_SCHEME("custom_url_scheme"),
    DEV("dev"),
    ENABLE_BLACK_LIST("enableBlacklist"),
    EXPERIMENTAL("experimental"),
    FDROID("fdroid"),
    FILE_RESTRICTION_ENABLED("file_restriction_enabled"),
    FILE_RESTRICTION_LIST("file_restriction_list"),
    FIREBASE_APP_ID("firebaseAppId"),
    FIREBASE_PUSH_SENDER_ID("firebasePushSenderId"),
    FORCE_APP_LOCK("force_app_lock"),
    FORCE_CONSTANT_BITRATE_CALLS("force_constant_bitrate_calls"),
    FORCE_HIDE_SCREEN_CONTENT("force_hide_screen_content"),
    FORCE_PRIVATE_KEYBOARD("force_private_keyboard"),
    HTTP_PROXY_PORT("http_proxy_port"),
    HTTP_PROXY_URL("http_proxy_url"),
    INTERNAL("internal"),
    KEEP_WEB_SOCKET_ON("keep_websocket_on"),
    MAX_ACCOUNTS("maxAccounts"),
    NEW_PASSWORD_MAXIMUM_LENGTH("new_password_maximum_length"),
    NEW_PASSWORD_MINIMUM_LENGTH("new_password_minimum_length"),
    PASSWORD_MAX_ATTEMPTS("password_max_attempts"),
    WIPE_ON_COOKIE_INVALID("wipe_on_cookie_invalid"),
    PROD("prod"),
    SUBMIT_CRASH_REPORTS("submitCrashReports"),
    SUPPORT_EMAIL("supportEmail"),
    TEAMS_URL("teamsUrl"),
    WEB_LINK_PREVIEW("web_link_preview"),
    WEBSITE_URL("websiteUrl"),
    WEB_SOCKET_URL("websocketUrl"),
    CERTIFICATE("certificate"),
    DOMAIN("domain"),
    COMMENT("_comment"),
    APP_NAME("appName"),
    APPLICATION_ID("applicationId"),
    DEVELOPER_FEATURES_ENABLED("developer_features_enabled"),
    LAUNCHER_ICON("launcherIcon"),
    LOGGING_ENABLED("logging_enabled"),
    SAFE_LOGGING("safe_logging"),
    USER_ID("userId")
}


