{
 "title": "Infinite Monkeys",
 "time": { "from": "now-4h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Conversations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    { "expr": "g_conversations", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Number of Members/Conversation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "avg by(id) (g_conversationMembers)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Errors per Actions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "max by(action) (c_errors_total)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Currently Logged Out Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max by(testCase, domain) (g_loggedOutUsers)",
     "legendFormat": "{{testCase}} - {{domain}}"
    }
   ]
  },
  {
   "title": "Currently Logged In Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "max by(testCase, domain) (g_loggedInUsers)",
     "legendFormat": "{{testCase}} - {{domain}}"
    }
   ]
  },
  { "title": "Actions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Distribution per 1m: Create Conversation time taken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_CREATE_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_CREATE_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_CREATE_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_CREATE_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "rate(t_CREATE_CONVERSATION_seconds_sum[1m])/rate(t_CREATE_CONVERSATION_seconds_count[1m])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Distribution per 1m: Destroy Conversation time taken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_DESTROY_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_DESTROY_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_DESTROY_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_DESTROY_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "rate(t_DESTROY_CONVERSATION_seconds_sum[1m])/rate(t_DESTROY_CONVERSATION_seconds_count[1m])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Distribution per 1m: Add User To Conversation time taken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_ADD_USERS_TO_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_ADD_USERS_TO_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_ADD_USERS_TO_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_ADD_USERS_TO_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "rate(t_ADD_USERS_TO_CONVERSATION_seconds_sum[1m])/rate(t_ADD_USERS_TO_CONVERSATION_seconds_count[1m])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Distribution per 1m: Leave Conversation time taken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_LEAVE_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_LEAVE_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_LEAVE_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_LEAVE_CONVERSATION_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "rate(t_LEAVE_CONVERSATION_seconds_sum[1m])/rate(t_LEAVE_CONVERSATION_seconds_count[1m])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Distribution per 1m: Send Messages time taken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_SEND_MESSAGE_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_SEND_MESSAGE_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_SEND_MESSAGE_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_SEND_MESSAGE_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "rate(t_SEND_MESSAGE_seconds_sum[1m])/rate(t_SEND_MESSAGE_seconds_count[1m])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Distribution per 1m: Send Request time taken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_SEND_REQUEST_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_SEND_REQUEST_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_SEND_REQUEST_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_SEND_REQUEST_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "rate(t_SEND_REQUEST_seconds_sum[1m])/rate(t_SEND_REQUEST_seconds_count[1m])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Distribution per 1m: Login time taken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_LOGIN_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_LOGIN_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_LOGIN_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_LOGIN_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "rate(t_LOGIN_seconds_sum[1m])/rate(t_LOGIN_seconds_count[1m])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Distribution per 1m: Reconnect time taken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_RECONNECT_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_RECONNECT_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_RECONNECT_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_RECONNECT_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "rate(t_RECONNECT_seconds_sum[1m])/rate(t_RECONNECT_seconds_count[1m])",
     "legendFormat": "Avg"
    }
   ]
  },
  { "title": "Kalium", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Distribution per 1m: Kalium - Create Conversation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_kalium_create_conversation_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_kalium_create_conversation_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_kalium_create_conversation_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_kalium_create_conversation_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "rate(t_kalium_create_conversation_seconds_sum[1m])/rate(t_kalium_create_conversation_seconds_count[1m])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Distribution per 1m: Kalium Destroy Conversation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_kalium_destroy_conversation_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_kalium_destroy_conversation_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_kalium_destroy_conversation_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_kalium_destroy_conversation_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "rate(t_kalium_destroy_conversation_seconds_sum[1m])/rate(t_kalium_destroy_conversation_seconds_count[1m])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Distribution per 1m: Kalium Leave Conversation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_kalium_leave_conversation_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_kalium_leave_conversation_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_kalium_leave_conversation_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_kalium_leave_conversation_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "rate(t_kalium_leave_conversation_seconds_sum[1m])/rate(t_kalium_leave_conversation_seconds_count[1m])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Distribution per 1m: Kalium Add Members to Conversation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_kalium_add_members_to_conversation_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_kalium_add_members_to_conversation_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_kalium_add_members_to_conversation_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_kalium_add_members_to_conversation_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "rate(t_kalium_add_members_to_conversation_seconds_sum[1m])/rate(t_kalium_add_members_to_conversation_seconds_count[1m])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Distribution per 1m: Kalium Remove Members from Conversation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_kalium_remove_members_from_conversation_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_kalium_remove_members_from_conversation_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_kalium_remove_members_from_conversation_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_kalium_remove_members_from_conversation_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "rate(t_kalium_remove_members_from_conversation_seconds_sum[1m])/rate(t_kalium_remove_members_from_conversation_seconds_count[1m])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Distribution per 1m: Kalium Get or Create 1:1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_kalium_get_create_dm_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_kalium_get_create_dm_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_kalium_get_create_dm_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_kalium_get_create_dm_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "rate(t_kalium_get_create_dm_seconds_sum[1m])/rate(t_kalium_get_create_dm_seconds_count[1m])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Distribution per 1m: Kalium Send Message",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_kalium_send_message_conversation_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_kalium_send_message_conversation_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_kalium_send_message_conversation_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_kalium_send_message_conversation_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "rate(t_kalium_send_message_conversation_seconds_sum[1m])/rate(t_kalium_send_message_conversation_seconds_count[1m])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Distribution per 1m: Kalium Send 1:1 Message",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(t_kalium_send_dm_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(t_kalium_send_dm_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(t_kalium_send_dm_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(t_kalium_send_dm_seconds_bucket[1m])))",
     "legendFormat": "p25"
    },
    {
     "expr": "rate(t_kalium_send_dm_seconds_sum[1m])/rate(t_kalium_send_dm_seconds_count[1m])",
     "legendFormat": "Avg"
    }
   ]
  }
 ]
}