apiVersion: 1

datasources:
    -   name: Prometheus
        uid: prometheusds
        type: prometheus
        url: http://prometheus:9090
        isDefault: true
        access: proxy
        editable: true
