/*
 * Wire
 * Copyright (C) 2024 Wire Swiss GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://www.gnu.org/licenses/.
 */

package com.wire.kalium.gradle.avs

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

public abstract class GenerateAvsXcodeConfigTask : DefaultTask() {
    @get:Internal
    public abstract val extractedXcframework: DirectoryProperty

    @get:InputFile
    @get:PathSensitive(PathSensitivity.NONE)
    public abstract val extractedXcframeworkMarker: RegularFileProperty

    @get:OutputFile
    public abstract val outputFile: RegularFileProperty

    @get:Input
    public abstract val macosMinimumVersion: Property<String>

    @TaskAction
    public fun generate() {
        val xcframeworkPath = extractedXcframework.get().asFile
            .resolve("avs.xcframework")
            .absolutePath
        val config = outputFile.get().asFile
        config.parentFile.mkdirs()
        val inherited = "${'$'}(inherited)"
        val frameworkDirectory = "${'$'}(KALIUM_AVS_XCFRAMEWORK_DIR)"
        val macos = AvsApplePlatform.MACOS.xcodePlatformPrefix
        val lines = listOf(
            "// Generated by com.wire.kalium.apple-avs-runtime.",
            "KALIUM_AVS_XCFRAMEWORK_DIR = $xcframeworkPath",
        ) + AvsApplePlatform.entries.map { platform ->
            "FRAMEWORK_SEARCH_PATHS[sdk=${platform.xcodePlatformPrefix}*] = " +
                "$inherited \"$frameworkDirectory/${platform.xcframeworkSlice}\""
        } + listOf(
            "OTHER_LDFLAGS = $inherited -framework avs",
        ) + AvsApplePlatform.entries.map { platform ->
            "LD_RUNPATH_SEARCH_PATHS[sdk=${platform.xcodePlatformPrefix}*] = " +
                "$inherited ${platform.xcodeRunpathSearchPath}"
        } + listOf(
            "MACOSX_DEPLOYMENT_TARGET[sdk=$macos*] = ${macosMinimumVersion.get()}",
        )
        config.writeText(lines.joinToString(separator = "\n", postfix = "\n"))
    }
}
