{{- if .Values.podMonitorIntegration.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: "{{ .Values.service.serverName }}-podmonitor"
  namespace: {{ .Values.namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.serverName }}
  podMetricsEndpoints:
    - path: /metrics
      port: monkeyport
  namespaceSelector:
    any: true
{{- end }}

---
{{- if .Values.podMonitorIntegration.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: "{{ .Values.service.controllerName }}-podmonitor"
  namespace: {{ .Values.namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.controllerName }}
  podMetricsEndpoints:
    - path: /
      port: monkeymetrics
  namespaceSelector:
    any: true
{{- end }}
