const fs = require("fs");
const path = require("path");

const coreCryptoNodeModules = require.resolve
    .paths("@wireapp/core-crypto")
    .find((candidate) => fs.existsSync(path.join(candidate, "@wireapp/core-crypto/package.json")));

if (!coreCryptoNodeModules) {
    throw new Error("Unable to locate @wireapp/core-crypto for its browser Wasm asset");
}

const coreCryptoWasm = path.join(
    coreCryptoNodeModules,
    "@wireapp/core-crypto/dist/browser/autogenerated/wasm-bindgen/index_bg.wasm"
);

config.resolve = config.resolve || {};
config.resolve.alias = {
    ...(config.resolve.alias || {}),
    "kalium-core-crypto-wasm$": coreCryptoWasm,
};
config.resolve.fallback = {
    ...(config.resolve.fallback || {}),
    fs: false,
    os: false,
    path: false,
};

config.module = config.module || {};
config.module.rules = config.module.rules || [];
config.module.rules.push({
    test: /index_bg\.wasm$/,
    type: "asset/resource",
});

config.experiments = {
    ...(config.experiments || {}),
    asyncWebAssembly: true,
};
