name: Benchmark Checks
on:
    merge_group:
    pull_request:
        types: [ opened, synchronize ]
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.merge_group.head_sha }}
    cancel-in-progress: true

jobs:
    detekt:
        uses: ./.github/workflows/codestyle.yml
    benchmarks-check:
        needs: [ detekt ]
        runs-on: ubuntu-latest
        container: wirebot/cryptobox:1.4.0
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup Java and Gradle
                uses: ./.github/actions/setup-java-gradle
            -   name: Run Benchmarks
                run: ./gradlew benchmark
            -   name: Generate HTML Report
                run: ./gradlew jmhReport
            -   name: Archive Reports
                if: always()
                uses: actions/upload-artifact@v4
                with:
                    name: benchmarks-reports
                    path: ./benchmarks/build/reports/benchmarks/**
            -   name: Create Benchmark Table
                id: benchmark-table
                uses: boswelja/kotlinx-benchmark-table-action@0.0.4
                with:
                    benchmark-results: ./benchmarks/build/reports/benchmarks/main/**/jvm.json
            -   name: Post Results
                run: |
                    echo '## Benchmarks results ⏱️' >> $GITHUB_STEP_SUMMARY
                    echo '${{steps.benchmark-table.outputs.benchmark-table}}️' >> $GITHUB_STEP_SUMMARY

            -   name: Cleanup Gradle Cache
                # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
                # Restoring these files from a GitHub Actions cache might cause problems for future builds.
                run: |
                    rm -f ~/.gradle/caches/modules-2/modules-2.lock
                    rm -f ~/.gradle/caches/modules-2/gc.properties
