name: "Gradle Run Tests"

on:
  pull_request:
    types: [ opened, synchronize ] # Don't rerun on `edited` to save time

jobs:
  gradle-run-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Native dependencies cache
        uses: actions/cache@v2
        id: cryptobox-cache
        with:
            path: |
              native/libs/libcryptobox-jni.dylib
              native/libs/libcryptobox.dylib
              /usr/local/lib/libsodium*
            key: cryptobox-sodium-build-macOS
      - name: Archive Cryptobox libs for debugging
        uses: actions/upload-artifact@v3
        with:
            name: native-libs
            path: native/libs
      - name: Archive LibSodium libs for debugging
        uses: actions/upload-artifact@v3
        with:
            name: sodium-libs
            path: /usr/local/lib/libsodium*
