name: "Auto Author Assign"
on:
  pull_request:
    types: [ opened, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # required by workflow defaults

jobs:
  assign-author:
    name: Assign Author
    permissions:
      pull-requests: write # required to assign the pull request author
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@3e19bfc990cb1cf0589dce95e9f75289bb1e22de
