name: "Semantic Commit Linting of PR titles"

on:
  merge_group:
    types: [ checks_requested ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # required for actions/checkout and repository metadata reads

jobs:
  semantic-commit-pr-title-lint-merge:
    name: semantic-commit-pr-title-lint
    runs-on: ubuntu-latest
    steps:
      - name: Skip semantic PR title check on merge queue
        run: echo "Skipping semantic PR title check on merge queue"
